version: '2'
services:
  db:
    image: mysql:5.7
    env_file: envs/.db.env
    container_name: db
    volumes:
      - ./db:/docker-entrypoint-initdb.d
    expose:
      - "3306"
  server:
    build: .
    image: marcoacierno/slaughterfield-ad:latest
    container_name: server
    volumes:
      - ./code/:/samp-svr/gamemodes/
    ports:
      - "7777:7777/udp"
    env_file: envs/.server.env
    links:
      - db:db
    depends_on:
      - db
