version: '2'
services:
  db:
    image: mysql:5.7
    env_file: /etc/samp-env/.db.env
    container_name: db
    volumes:
      - /home/marco/db:/docker-entrypoint-initdb.d
    expose:
      - "3306"
    links:
      - server:server
  server:
    image: marcoacierno/slaughterfield-ad:latest
    container_name: server
    ports:
      - "7777:7777/udp"
    env_file: /etc/samp-env/.server.env
    depends_on:
      - db
