version: "2"
services: 
  db: 
    container_name: db
    env_file: envs/.db.env
    expose: 
      - "3306"
    image: "mysql:5.7"
    volume_driver: local
    volumes: 
      - ./db:/docker-entrypoint-initdb.d
      - "mysqldata:/var/lib/mysql"
  server: 
    build: "."
    container_name: server
    depends_on: 
      - db
    env_file: envs/.server.env
    image: "marcoacierno/slaughterfield-ad:latest"
    links: 
      - "db:db"
    ports: 
      - "7777:7777/udp"
volumes: 
  mysqldata: 
    driver: local
